/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.IOFile;
import java.io.File;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Book;
import model.QLMS;
import model.Reader;

/**
 *
 * @author DELL
 */
public class FormQLM extends javax.swing.JPanel {

    /**
     * Creates new form FormBook
     */
    private DefaultTableModel tm;
    private boolean them,ok;
    private String file;
    
    public FormQLM() {
        initComponents();
        setSize(900,600);
        String[] cols={
            "ma reader","ho ten","ma sach","so luong","tinh trang"
        };
        tm=new DefaultTableModel(cols,0);
        jTable1.setModel(tm);
        buttonTrue();
        them=false;
        file="src/controller/bqlm.dat";
        loadMa();
        
    }
    public void loadMa(){
        List<Reader> list=IOFile.docra("src/controller/reader.dat");
        jComboBox1.removeAllItems();
        for(Reader i:list){
            jComboBox1.addItem(i.getMa()+"");
        }
        List<Book> list1=IOFile.docra("src/controller/book.dat");
        jComboBox2.removeAllItems();
        for(Book i:list1){
            jComboBox2.addItem(i.getMa()+"");
        }
    }
    private void buttonTrue(){
        btnThem.setEnabled(true);
        BtnCapnhat.setEnabled(false);
        btnBoqua.setEnabled(false);
    }
    private void buttonFalse(){
        btnThem.setEnabled(false);
        BtnCapnhat.setEnabled(true);
        btnBoqua.setEnabled(true);
    }
    private Reader getReaderbyMa(int ma){
        List<Reader> list= IOFile.docra("src/controller/reader.dat");
        for(Reader i:list){
            if(i.getMa()==ma){
                return i;
            }
        }
        return null;
    }
    private Book getBookbyma(int ma){
        List<Book> list= IOFile.docra("src/controller/book.dat");
        for(Book i:list){
            if(i.getMa()==ma){
                return i;
            }
        }
            return null;
    }
    private List<QLMS> getAll(){
        List<QLMS> list= new ArrayList<>();
        for(int i=0;i<tm.getRowCount();i++){
            int mbd=Integer.parseInt(tm.getValueAt(i, 0).toString());
            int mas=Integer.parseInt(tm.getValueAt(i, 2).toString());
            Reader r=getReaderbyMa(mbd);
            Book b=getBookbyma(mas);
            int sl=Integer.parseInt(tm.getValueAt(i, 3).toString());
            String tt=tm.getValueAt(i, 4).toString();
            QLMS q=new QLMS(r, b, sl, tt);
            list.add(q);
            
        }
        return list;
    }
        
    private boolean existed(int mabd,int mas){
        List<QLMS> list= getAll();
        for(QLMS i:list){
            if(i.getReader().getMa()==mabd&&i.getBook().getMa()==mas){
                return true;
            }
        }
        return false;
    }
    private int getDauSach(int mabd){
        int count=0;
        List<QLMS> list=getAll();
        for(QLMS i: list){
            if(i.getReader().getMa()==mabd)
                count++;
        }
        return count;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTinhTrang = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        btnLammoi = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        BtnCapnhat = new javax.swing.JButton();
        btnBoqua = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnHienthi = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        btnsapxep = new javax.swing.JButton();
        jComboBox4 = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("ma reader");

        jLabel2.setText("ma book");

        jLabel3.setText("so luong");

        jLabel5.setText("tinh trang");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        btnLammoi.setText("lam moi");
        btnLammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLammoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLammoi)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnLammoi)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        btnThem.setText("them");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        BtnCapnhat.setText("cap nhat");
        BtnCapnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCapnhatActionPerformed(evt);
            }
        });

        btnBoqua.setText("bo qua");
        btnBoqua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoquaActionPerformed(evt);
            }
        });

        btnLuu.setText("luu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnHienthi.setText("hien thi");
        btnHienthi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienthiActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("theo so luong muon");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("theo ten ban doc");

        btnsapxep.setText("sap xep");
        btnsapxep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsapxepActionPerformed(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sx theo so luong muon", "sx theo ten ban doc" }));
        jComboBox4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox4ItemStateChanged(evt);
            }
        });
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLuu)
                    .addComponent(btnThem))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BtnCapnhat)
                        .addGap(37, 37, 37)
                        .addComponent(btnBoqua)
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioButton2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(120, 120, 120))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnHienthi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnsapxep)
                        .addGap(349, 349, 349))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem)
                            .addComponent(BtnCapnhat)
                            .addComponent(btnBoqua)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jRadioButton1)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLuu)
                            .addComponent(btnHienthi))
                        .addContainerGap(41, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnsapxep)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)
                        .addGap(25, 25, 25))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        buttonFalse();
        them=true;
        jComboBox1.requestFocus();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnBoquaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoquaActionPerformed
        // TODO add your handling code here:
        
           buttonTrue();
           them=false;
     
    }//GEN-LAST:event_btnBoquaActionPerformed

    private void BtnCapnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCapnhatActionPerformed
        // TODO add your handling code here:
        if(them){
            int mabd=Integer.parseInt(jComboBox1.getSelectedItem().toString());
            int mas=Integer.parseInt(jComboBox2.getSelectedItem().toString());
            if(existed(mabd, mas)||getDauSach(mabd)>5){
                JOptionPane.showMessageDialog(this, "khong nhap dc nua!!");
            }else{
                Reader r=getReaderbyMa(mabd);
                Book b= getBookbyma(mas);
                int sl=Integer.parseInt(jComboBox3.getSelectedItem().toString());
                 String tt=txtTinhTrang.getText();
                 QLMS q=new QLMS(r, b, sl, tt);
                 tm.addRow(q.toObject());
                 buttonTrue();
                them=false;
            }
        
        }
    }//GEN-LAST:event_BtnCapnhatActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        List<QLMS> list= getAll();
        
      IOFile.vietvao(file, list);
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnHienthiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienthiActionPerformed
        // TODO add your handling code here:
        List<QLMS> list=IOFile.docra(file);
        tm.setRowCount(0);
        for(QLMS i:list){
            tm.addRow(i.toObject());
        }
    }//GEN-LAST:event_btnHienthiActionPerformed

    private void btnLammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLammoiActionPerformed
        // TODO add your handling code here:
        loadMa();
    }//GEN-LAST:event_btnLammoiActionPerformed

    private void btnsapxepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsapxepActionPerformed
        // TODO add your handling code here:
        List<QLMS> list=getAll();
        if(jRadioButton1.isSelected()){
            //theo sl sach
            list.sort(new Comparator<QLMS>() {
                @Override
                public int compare(QLMS o1, QLMS o2) {
                    return o1.getSl()-o2.getSl();
                }
            });
        }else{
            list.sort(new Comparator<QLMS>() {
                @Override
                public int compare(QLMS o1, QLMS o2) {
                    String t1=o1.getReader().getHoTen();
                    String t2=o2.getReader().getHoTen();
                    String ten1=t1.substring(t1.lastIndexOf(" ")+1)+t1;
                    //String ten1=t1.substring(t1.lastIndexOf(" ")+1)+t1;
                    String ten2=t2.substring(t2.lastIndexOf(" ")+1)+t2;
                    return ten1.compareToIgnoreCase(ten2);
                }
            });
        }
        tm.setRowCount(0);
        for(QLMS i:list){
            tm.addRow(i.toObject());
        }
    }//GEN-LAST:event_btnsapxepActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox4ItemStateChanged
        // TODO add your handling code here:
        List<QLMS> list=getAll();
        if(jComboBox4.getSelectedIndex()==0){
            //theo sl sach
            list.sort(new Comparator<QLMS>() {
                @Override
                public int compare(QLMS o1, QLMS o2) {
                    return o1.getSl()-o2.getSl();
                }
            });
        }else{
            list.sort(new Comparator<QLMS>() {
                @Override
                public int compare(QLMS o1, QLMS o2) {
                    String t1=o1.getReader().getHoTen();
                    String t2=o2.getReader().getHoTen();
                    String ten1=t1.substring(t1.lastIndexOf(" ")+1)+t1;
                    String ten2=t2.substring(t2.lastIndexOf(" ")+1)+t2;
                    return ten1.compareToIgnoreCase(ten2);
                }
            });
        }
        tm.setRowCount(0);
        for(QLMS i:list){
            tm.addRow(i.toObject());
        }
    }//GEN-LAST:event_jComboBox4ItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCapnhat;
    private javax.swing.JButton btnBoqua;
    private javax.swing.JButton btnHienthi;
    private javax.swing.JButton btnLammoi;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnsapxep;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtTinhTrang;
    // End of variables declaration//GEN-END:variables
}
